"""empty message

Revision ID: 36670f5ec437
Revises: 78223e585a31
Create Date: 2020-12-09 20:04:30.225872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36670f5ec437'
down_revision = '78223e585a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verify_email',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('confirmed_email', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verify_email')
    # ### end Alembic commands ###
