"""Initial migration.

Revision ID: 4b35bf381311
Revises: 
Create Date: 2020-10-23 13:19:28.104279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b35bf381311'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('vendible', sa.Boolean(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('autor', sa.String(), nullable=True),
    sa.Column('editorial', sa.String(), nullable=True),
    sa.Column('sinopsis', sa.String(), nullable=True),
    sa.Column('fecha_de_publicacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
