"""empty message

Revision ID: 5c8181c7f31d
Revises: d2c623f86b32
Create Date: 2020-11-04 22:32:28.114954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8181c7f31d'
down_revision = 'd2c623f86b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('library_type', sa.Enum('Bought', 'Wish List', name='library_types'), nullable=False))
    op.add_column('library', sa.Column('state', sa.Enum('Pending', 'Reading', 'Finished', 'Dropped', name='state_types'), nullable=False))
    op.add_column('library', sa.Column('visible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'visible')
    op.drop_column('library', 'state')
    op.drop_column('library', 'library_type')
    # ### end Alembic commands ###
