"""empty message

Revision ID: c56d9902b45b
Revises: 4b35bf381311
Create Date: 2020-10-26 15:58:00.253484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56d9902b45b'
down_revision = '4b35bf381311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('url_imagen', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'url_imagen')
    # ### end Alembic commands ###
