"""empty message

Revision ID: ef6887ce219c
Revises: 34e2cbf1b8b8
Create Date: 2020-11-12 19:24:06.759124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6887ce219c'
down_revision = 'c384ba7f77e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_recovery',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_recovery')
    # ### end Alembic commands ###
